# Generated by Django 3.0.5 on 2023-11-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='bookingmaster',
            fields=[
                ('bookingmaster_id', models.AutoField(primary_key=True, serialize=False)),
                ('bm_date', models.DateField(default='2023-10-10')),
                ('bm_total', models.CharField(max_length=56)),
                ('login_id', models.CharField(max_length=56)),
                ('bm_status', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='farmer_eartag_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('regidate', models.DateField()),
                ('dob', models.DateField()),
                ('colour', models.CharField(max_length=50)),
                ('sire_id', models.CharField(max_length=50)),
                ('pregnancy', models.CharField(max_length=50)),
                ('pregnancymonth', models.CharField(max_length=50)),
                ('milkingstatus', models.CharField(max_length=50)),
                ('eartag_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('usertype', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.CharField(max_length=200)),
                ('product_price', models.CharField(max_length=100)),
                ('product_quantity', models.CharField(max_length=100)),
                ('product_category', models.CharField(default='Dairy', max_length=100)),
                ('product_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.login')),
                ('PRODUCTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.Products')),
            ],
        ),
        migrations.CreateModel(
            name='farmer_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_first_name', models.CharField(max_length=50)),
                ('farmer_last_name', models.CharField(max_length=50)),
                ('farmer_email', models.EmailField(max_length=254, null=True)),
                ('farmer_phone', models.CharField(max_length=10)),
                ('farmer_category', models.CharField(max_length=10)),
                ('farmer_aadar', models.IntegerField()),
                ('farmer_address', models.CharField(max_length=200)),
                ('farmer_district', models.CharField(max_length=100)),
                ('farmer_state', models.CharField(max_length=100)),
                ('farmer_country', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='farmer_health_checkups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_condition', models.CharField(max_length=200)),
                ('symptoms', models.CharField(max_length=200)),
                ('additional_services', models.CharField(max_length=50)),
                ('nearby_hospital', models.CharField(max_length=100)),
                ('prefered_date', models.DateField()),
                ('check_status', models.CharField(max_length=50)),
                ('eartag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_eartag_application')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_registration')),
            ],
        ),
        migrations.CreateModel(
            name='farmer_eartag_re_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_eartag_no', models.CharField(max_length=20)),
                ('prev_eartag_regi_date', models.CharField(max_length=60)),
                ('new_eartag_regi_date', models.CharField(max_length=60)),
                ('missing_date', models.CharField(max_length=50)),
                ('additional_details', models.CharField(max_length=200)),
                ('eartag_miss_status', models.CharField(max_length=50)),
                ('eartag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_eartag_application')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_registration')),
            ],
        ),
        migrations.AddField(
            model_name='farmer_eartag_application',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_registration'),
        ),
        migrations.CreateModel(
            name='farmer_AI_re_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nearby_hospital', models.CharField(max_length=50)),
                ('prev_insemination_date', models.CharField(max_length=20)),
                ('reason_for_re_request', models.CharField(max_length=200)),
                ('prefered_date', models.DateField()),
                ('ai_re_status', models.CharField(max_length=20)),
                ('eartagai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_eartag_application')),
                ('farmerai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_registration')),
            ],
        ),
        migrations.CreateModel(
            name='farmer_AI_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_date', models.DateField()),
                ('near_veterinary_hospital', models.CharField(max_length=100)),
                ('inseminated_before', models.CharField(max_length=10)),
                ('is_first_insemination', models.CharField(max_length=10)),
                ('no_of_inseminations', models.CharField(max_length=10)),
                ('ai_status', models.CharField(max_length=10)),
                ('eartagai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_eartag_application')),
                ('farmerai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.farmer_registration')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.login')),
                ('PRODUCTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.Products')),
            ],
        ),
        migrations.CreateModel(
            name='booking_child',
            fields=[
                ('bookingchild_id', models.AutoField(primary_key=True, serialize=False)),
                ('bc_qty', models.CharField(max_length=56)),
                ('bc_amount', models.CharField(max_length=65)),
                ('bookingmaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.bookingmaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.Products')),
            ],
        ),
    ]
