# Generated by Django 3.0.5 on 2023-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_auto_20231110_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_registration',
            name='farmer_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
