# Generated by Django 3.0.5 on 2023-11-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0003_auto_20231110_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(),
        ),
    ]
