# Generated by Django 3.0.5 on 2023-11-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0005_auto_20231110_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_ai_re_application',
            name='prev_insemination_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='farmer_ai_re_application',
            name='reason_for_re_request',
            field=models.TextField(),
        ),
    ]
