# Generated by Django 3.0.5 on 2023-11-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0006_auto_20231110_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmaster',
            name='bm_total',
            field=models.FloatField(),
        ),
    ]
