# Generated by Django 3.0.5 on 2023-11-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0007_auto_20231110_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_child',
            name='bc_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking_child',
            name='bc_qty',
            field=models.IntegerField(),
        ),
    ]
