# Generated by Django 3.0.5 on 2023-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0008_auto_20231110_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='cvv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='number',
            field=models.IntegerField(),
        ),
    ]
