# Generated by Django 3.0.5 on 2023-11-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0009_auto_20231110_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=50)),
                ('daddress', models.CharField(max_length=50)),
                ('dplace', models.EmailField(max_length=254, null=True)),
                ('dpin', models.BigIntegerField()),
                ('ddistrict', models.CharField(max_length=10)),
                ('dphone', models.BigIntegerField()),
                ('dpost', models.CharField(max_length=200)),
                ('demail', models.CharField(max_length=100)),
                ('dstate', models.CharField(max_length=100)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.bookingmaster')),
            ],
        ),
    ]
