# Generated by Django 3.0.5 on 2023-11-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0010_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='balance',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='cvv',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
