# Generated by Django 3.0.5 on 2023-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0011_auto_20231117_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_address',
            name='ddistrict',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='demail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='dpin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='dplace',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='dpost',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='delivery_address',
            name='dstate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer_eartag_re_application',
            name='prev_eartag_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
